### ISSUE TITLE
realmadryt.pl

### ISSUE THREAD

**Issue by LuisPro** [olegwukr/polish-privacy-filters#102]
https://www.realmadryt.pl/news/91209-zidane-przestancie-opowiadac-ze-nie-licze-na-viniciusa

pls do something so we can read articles and comments but not see ads. ty.

**Comment by krystian3w** [comment]
https://github.com/olegwukr/polish-privacy-filters/commit/c059ce56d83be2e54291158170e22ac63878292e

**Comment by krystian3w** [comment]
@olegwukr 

`@@||realmadryt.pl^$xmlhttprequest,domain=realmadryt.pl`
