### ISSUE TITLE
expressilustrowany.pl

### ISSUE THREAD

**Issue by hawkeye116477** [olegwukr/polish-privacy-filters#105]
`https://expressilustrowany.pl/wjechal-w-honde-i-w-przystanek-autobusowy-na-al-wlokniarzy-wiata-do-wymiany/ar/c1-14432815`
![Screenshot_20190918_175500](https://user-images.githubusercontent.com/19818572/65164563-727a7900-da3d-11e9-93f3-67940b1f5177.png)

**Comment by krystian3w** [comment]
`@@||ppstatic.pl/assets/nsk/*/js/compiled/atoms/ads/branding-video.js`

Jak nie chcemy się bawić w kosmetykę / generichide.

--

uBO / AdGuard z problematyczną w przyszłości kosmetyką:

```
||ppstatic.pl/assets/nsk/*/js/compiled/atoms/ads/branding-video.js$script,domain=pl,eu,redirect=noopjs,important
polskatimes.pl,dziennikbaltycki.pl,expressilustrowany.pl#@##advert1
polskatimes.pl,dziennikbaltycki.pl,expressilustrowany.pl#@#.div-gpt-ad
```

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/14761

**Comment by krystian3w** [comment]
Wynalazek od @llacb47:

`pl,eu##+js(abort-current-inline-script.js, atob, googlefc)`

https://github.com/NanoMeow/QuickReports/issues/1622

**Comment by hawkeye116477** [comment]
Raczej wstrzykiwanie skryptów do wszystkich domen eu i pl to niezbyt dobry pomysł.

**Comment by krystian3w** [comment]
~66 ich domen można zawsze wziąć z ich pliku pod ABP "`@@||*$document`".
