### ISSUE TITLE
pol-news24.pl

### ISSUE THREAD

**Issue by ggargul** [olegwukr/polish-privacy-filters#106]
Anty-adblock: "Strona ta utrzumuje się jedynie z reklam które są  tu umieszczone Więc nie blokuj ich Zamknij Komunikat"
Przykładowy artykuł: https://pol-news24.pl/roman-giertych-zadrwil-z-blaszczaka-na-twitter/

![adbl](https://user-images.githubusercontent.com/51117730/65815991-b700d400-e1f6-11e9-9e92-573596e9dc32.png)

**Comment by gargul2** [comment]
https://github.com/PolishFiltersTeam/KAD/issues/1476
