### ISSUE TITLE
https://tibiopedia.pl/forum

### ISSUE THREAD

**Issue by LuisPro** [olegwukr/polish-privacy-filters#107]
![2019-09-29 15_14_06-Forum - Tibia ~ Tibiopedia pl](https://user-images.githubusercontent.com/6198792/65833079-5774f800-e2cc-11e9-92e5-bc890fc81d39.png)

kod tego komunikatu zawsze się zmienia, jest jakaś rada żeby go na stałe zablokować?
wyskakuje tylko raz dziennie ale wkurza,

**Comment by krystian3w** [comment]
to było naprawione w filtrach Nano Defender, widać oleg nie dokopiuje:

https://jspenguin2017.github.io/uBlockProtector/#extra-installation-steps-for-ublock-origin
