### ISSUE TITLE
add support for adguard

### ISSUE THREAD

**Issue by KonoromiHimaries** [olegwukr/polish-privacy-filters#110]
https://github.com/AdguardTeam/CoreLibs/issues/152

example
`||example.org^$document,subdocument,popup`

**Comment by krystian3w** [comment]
All w sumie odpada tak długo aż tego nie naprawią:

https://github.com/AdguardTeam/FiltersCompiler/issues/58

Raczej nikt nie subskrybuje list manualnie (no chyba, że ten do Polskiej prywatności po prostu na liście nie ma).

**Comment by hawkeye116477** [comment]
Jeszcze chyba jest taki problem => `https://github.com/AdguardTeam/CoreLibs/issues/152#issuecomment-542626310`
