### ISSUE TITLE
shinden.pl

### ISSUE THREAD

**Issue by pepek1122583** [olegwukr/polish-privacy-filters#116]
https://shinden.pl/episode/8608-baka-to-test-to-shoukanjuu/view/73637#column-one-inner

Podczas uruchamiania playera
![image](https://user-images.githubusercontent.com/21297574/81335301-b0e5a680-90a7-11ea-9044-6f5eed248b40.png)

**Comment by kulfoon** [comment]
To wyskakuje na Adblock Plus, a ponoć [już dawno temu zmieniłeś na Ublock Origin](https://github.com/MajkiIT/polish-ads-filter/issues/14806#issuecomment-538570005), czyżbyś znowu wrócił na stare graty - Adblock Plus, tego się nie naprawi w ułomnym Adblock Plus, a jeśli ci to wyskakuje na uBO to jakaś dodatkowa lista ci to powoduje.

**Comment by kulfoon** [comment]
Nie wiem po co ten pajac krystian3w [duplikuje wątki](https://github.com/MajkiIT/polish-ads-filter/issues/16286), a z kolei [tutaj](https://github.com/NanoMeow/QuickReports/issues/3802#issuecomment-626859780) wkleja linki do swojego duplikatu, typ chyba odleciał...

**Comment by pepek1122583** [comment]
A to przepraszam :X Nie widzialem otwartego ticketu. Proszę o nie bicie :X

**Comment by kulfoon** [comment]
@pepek1122583 , spoko, nie musisz przepraszać, ty nic złego nie zrobiłeś, po prostu błędnie odczytałeś mój komentarz, wyraźnie napisałem w nim, że to ten gość: **krystian3w** zduplikował twój wątek, a nie ty jego, bo ty byłeś pierwszy ze swoim wątkiem, więc to on powinien zamknąć swój wątek, a nie ty, więc możesz swój wątek otworzyć jeśli chcesz. I doceniam także twoją kulturę i wychowanie, takich ludzi jak ty się szanuje, przepraszasz i zamykasz wątek, kiedy robić to powinni tacy spamerzy jak Janasek i krystian3w, ale daleko im do twojego wychowania.
