### ISSUE TITLE
player.pl

### ISSUE THREAD

**Issue by metiuPL** [olegwukr/polish-privacy-filters#119]
Mam wgranego nanodefender i nanoadblocker - do tego wgrane filtry:
- Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
- Polskie Filtry Anty-Adblockowe
- Polskie Filtry Społecznościowe
- Polskie Filtry Elementów Irytujących
- Polskie Filtry Prywatności

Player.pl po kilku sekundach przerywa i rzuca informacją o adblockerze (co ciekawe jak się przełączy na pełny ekran to takiego komunikatu nie ma). 

Zauważyłem, że zmienił mi się wygląd odtwarzacza i mogę skopiować takie informacje:

NuviVersion: 2.5.5
Browser: Chrome 84
Operating System: Windows 10
Device: Desktop
AdBlock: true

**Comment by metiuPL** [comment]
> Zalecany **uBlock Origin** lub **AdGuard**.
> 
> ABP i AdBlock nie mają opcji by problem naprawić bez dopuszczenia "mnóstwa śmieci".
> To też niewiele wnosi - https://gitlab.com/eyeo/adblockplus/adblockpluscore/-/issues/225 (tylko lista anti-CV może użyć).

Sprawdzałem uBlock Origin i AdGuard - niestety nie pomogło. Póki co rozwiązanie jest tylko takie jak podałem powyżej - włączenie trybu pełnego ekranu. Do momentu minimalizacji lub zatrzymania odtwarzania jakoś trzyma blokadę.

> Nowy wygląd jest chyba tylko z polskim IP.

Nie wiem dlaczego mam inny wygląd. Sprawdzałem player.pl na dwóch komputerach oddalonych od siebie o jakieś 10km (oba w PL) i na jednym mam stary wygląd, a na drugim nowy. Przeglądarki identyczne, wtyczki identyczne, system i stan aktualizacji systemu identyczne - w zasadzie bliźniacze komputery poza "wnętrznościami".

**Comment by gargul2** [comment]
I w końcu po długim czasie mi też wyskoczył kilka razy anty-adblock razem z tym nowym wyglądem odtwarzcza video: https://github.com/NanoMeow/QuickReports/issues/2453#issuecomment-686575454, ale potem przestał się pojawiać, więc nie wiem na jakiej zasadzie się pojawia, może jakoś losowo.

**Comment by metiuPL** [comment]
> I w końcu po długim czasie, dzisiaj, mi też wyskoczył kilka razy anty-adblock [NanoMeow/QuickReports#2453 (comment)](https://github.com/NanoMeow/QuickReports/issues/2453#issuecomment-686575454), razem z tym nowym wyglądem odtwarzcza video, ale potem przestał się pojawiać, więc nie wiem na jakiej zasadzie się pojawia, może jakoś losowo. (Firefox 80.0.1 & uBO 1.29.2)

Miałem pisać - coś się w tej kwestii zmieniło, bo:
- w drugim miejscu pojawił mi się nowy odtwarzacz
- w obu miejscach jest zdecydowanie lepiej, bo zawiesza się dużo rzadziej (póki co raptem raz)

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/63179 + https://github.com/AdguardTeam/AdguardFilters/commit/8c71d9217322cb9f00247b5ec28f6b6606b54eec

**Comment by gargul2** [comment]
Jeśli chodzi o mnie, to nie mam jak zweryfikować, czy ta odtrutka działa, bo jak już pisałem, anty-adblock u mnie przestał się pojawiać, być może metiuPL będzie mógł zwerfyikować odtrutkę.

A przy okazji chciałem trochę wyładować złość wywołaną przez ten nowy odtwarzacz video, wyobraźcie sobie, że to ścierwo samo bez pytania się włącza, już kilka razy mi się to przydarzyło w ciągu jednego dnia:
- miałem zapauzowany player.pl, przełączyłem się do innej zakładki, i przeglądam inną stronę, po jakimś czasie słyszę, że coś mi się w przeglądarce odtwarza, sprawdzam różne zakładki, no ni huja nic się nie odtwarza, zaglądam do player.pl a to hujostwo leci !!! myślę co do huja , i zapauzowałem drugi raz, ale po jakimś czasie sytuacja się powtórzyła, no kurwa to już nie poważne
- szczyt kurestwa nastąpił dziś rano gdy siadam do kompa (kompa mam włączonego zawsze 24 na dobę, jak lodówkę) - słyszę, znowu coś leci, patrzę a tu znowu player.pl, leciał całą noc, przeleciało kilkanaście odcinków, całą noc kurestwo łącze obciążało

**Comment by metiuPL** [comment]
Na tym etapie wszystko działa tak jak powinno. Nie instalowałem Adguarda - mam nadal tylko nanodefender i nanoadblocker z filtrami jak powyżej, czyli także Adguardowymi. 

Sprawa można śmiało powiedzieć zakończona - dzięki!
