### ISSUE TITLE
magazyn.wp.pl adblock detection

### ISSUE THREAD

**Issue by Sergey-Lyapin** [olegwukr/polish-privacy-filters#120]
It seems that scriptlets below cause adblock detection on magazyn.wp.pl
```
#%#//scriptlet('ubo-set.js', 'Object.prototype.advViewability', 'undefined')
#%#//scriptlet('ubo-abort-on-property-read.js', 'Object.prototype.rebuild')
#%#//scriptlet('ubo-abort-on-property-read.js', 'asname')
```

AdGuard issue: https://github.com/AdguardTeam/AdguardFilters/issues/62046

**Comment by krystian3w** [comment]
@olegwukr / @MajkiIT uAsset też rozważa dezaktywacje w `uBlock filters -- unbreak`.

**Comment by gargul2** [comment]
Duplikat tego: https://github.com/olegwukr/polish-privacy-filters/issues/81

**Comment by MajkiIT** [comment]
@krystian3w to nie pomaga ?
https://github.com/olegwukr/polish-privacy-filters/commit/4a3770aca04bd0143340fa7f1073dedde2e381cb#diff-bde4d2ca165ca262b121296ccf4d1bc8

**Comment by krystian3w** [comment]
Myślę, że to jest trochę za mało (działa tylko na jedną subdomenę), plansza miga na `money` czy `kuchnia wp`:

`https://www.money.pl/gospodarka/ministerstwo-zmienia-strategie-6550100938537856a.html`
https://user-images.githubusercontent.com/35370833/92148224-908ee400-ee1c-11ea-86ca-dac3e08ba6a9.png

`https://kuchnia.wp.pl/sniadanie-do-szkoly-6549682327985024a`
https://user-images.githubusercontent.com/35370833/92148406-d186f880-ee1c-11ea-98ae-5e15f4027888.png


Pewnie kwestia czasu jak się nagle uruchomi da druga co odświeżenie (chyba że ją pogrzebali).

**Comment by gargul2** [comment]
Anty-adblock wyskakuje nadal.

**Comment by MajkiIT** [comment]
@krystian3w @gargul2 a z aktualnymi filtrami i po 2 odświeżeniu nie znika ? 

https://github.com/olegwukr/polish-privacy-filters/issues/121

**Comment by gargul2** [comment]
Po 2 odświeżeniu znika na `money.pl` https://github.com/olegwukr/polish-privacy-filters/issues/121, ale na `magazyn.wp.pl` wyskakuje nadal, wczoraj wynalazłem odtrutkę, ale dzisiaj już przestała działać.

**Comment by krystian3w** [comment]
Sprawna odtrutka jest w AdGuard Base, pewnie wyłączają połowę skryptletów przestarzałych i używają swoich zaktualizowanych.

Nie mam na myśli `replace`, bo działa z uBO - czyli pewnie coś z:
* skryptlet 
* `redirect` 
* dopuszczenie sieciowe 
* blokada sieciowa zasobu lub żądania 
* opcjonalnie CSS z braku interaktywnych elementów na magazynie np. komentarze.

**Comment by gargul2** [comment]
Jakoś nie widzę sprawności tej odtrutki, po włączeniu AdGuard Base, dalej jest anty-adblock.
