### ISSUE TITLE
||freshmail.mx^

### ISSUE THREAD

**Issue by bug-rules** [olegwukr/polish-privacy-filters#124]
https://github.com/olegwukr/polish-privacy-filters/blob/d8efbbe37b8d5416fb9ddf06df67e5fa3acb12ad/adblock.txt#L76

Filtr za mocno chroni prywatność, blokując wszelkie osadzone  zdjęcia w newsletterach.

`http://mail.mailnews.pl/test-preview/t5oodolvnp/n11qcvx5ew/`

![Ogólnopolski Dzień Informacyjny](https://user-images.githubusercontent.com/66819865/97565053-dc59a600-19e5-11eb-9427-81857229d35e.png) | ![Ogólnopolski Dzień Informacyjny](https://user-images.githubusercontent.com/66819865/97565057-dd8ad300-19e5-11eb-8f02-95b2b4b0b7cc.png)
--- | ---
brak grafik | po odblokowaniu grafik

**Comment by zaba-monika** [comment]
@MajkiIT @olegwukr

**Comment by zaba-monika** [comment]
- naprawione w https://github.com/olegwukr/polish-privacy-filters/commit/4c68b5509e7b94b299fed569e5c761c6baa633a2
- autor zgłoszenia zaktualizuj listę 
- i możesz zamknąć już zgłoszenie
