### ISSUE TITLE
gosc.pl

### ISSUE THREAD

**Issue by pwilkin** [olegwukr/polish-privacy-filters#125]
https://www.gosc.pl/doc/6621341.Ludzie-nauki-w-obronie-Jana-Pawla-II?fbclid=IwAR02RPWEZSd5u1JEZDLf-cnbEcBuCo8YPbKeUCF6754z3AztE_pPyTrnbQQ****

**Comment by zaba-monika** [comment]
Listy, które powodują anty-adlblocka to:
- POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
- AdGuard Base

Naprawa: `@@||request.dqst.pl/v1/*$xmlhttprequest,domain=www.gosc.pl`

@MajkiIT

**Comment by zaba-monika** [comment]
- naprawione w https://github.com/olegwukr/polish-privacy-filters/commit/4c68b5509e7b94b299fed569e5c761c6baa633a2
- @pwilkin zaktualizuj listę 
- i możesz zamknąć już zgłoszenie
