### ISSUE TITLE
www.ing.pl

### ISSUE THREAD

**Issue by krystian3w** [olegwukr/polish-privacy-filters#126]
## Problem:

Na stronie głównej jest psuty slider.

![obraz](https://user-images.githubusercontent.com/35370833/102027504-d278e000-3da4-11eb-8ad2-0eb97b9a178b.png) |
--- |

## Rozwiązania:

    @@||adocean-pl.hit.gemius.pl^$xmlhttprequest,domain=www.ing.pl

~~uBO obsługuje niby poprawnie to (ale lista nie obsługuje składni uBO jeszcze):~~

~~`||hit.gemius.pl^$xhr,domain=www.ing.pl,redirect=noop.txt,important`~~ (trzeba czyścić domenę gemius, by stwierdzić, że to nie działa).

Problematyczne - psujące stronę:

> https://github.com/olegwukr/polish-privacy-filters/blob/619ec443ab376751faae3f3da36a5a742771cbd8/adblock.txt#L84 i https://github.com/olegwukr/polish-privacy-filters/blob/619ec443ab376751faae3f3da36a5a742771cbd8/adblock.txt#L82

---

~~Przy okazji:~~

~~Duplikaty funkcji (drugi filtr blokuje więcej np. żądania `XHR`):~~

> https://github.com/olegwukr/polish-privacy-filters/blob/619ec443ab376751faae3f3da36a5a742771cbd8/adblock.txt#L38 ~~a~~ https://github.com/olegwukr/polish-privacy-filters/blob/619ec443ab376751faae3f3da36a5a742771cbd8/adblock.txt#L84

**Comment by MajkiIT** [comment]
https://github.com/olegwukr/polish-privacy-filters/commit/f6080227fd3c7b4c1f370d5b328a5966f6d73164#diff-cc474e426ece5e503e669e76f244564cb7218008ac11213fd82ac4c65ad3c494

https://github.com/olegwukr/polish-privacy-filters/commit/83e307b1c8d24f55c15fa61b0fdd6e88266bdea7#diff-cc474e426ece5e503e669e76f244564cb7218008ac11213fd82ac4c65ad3c494

**Comment by krystian3w** [comment]
W sumie jest problem, jednak plik "json" musi się załadować:

```json
{

"Rotator_1":{
    "buttonStyle": "indigo",
    "buttonLabel": "w aplikacji Moje ING",
    "buttonAriaLabel": "",

    "disclaimerText": "",

    "headlineBarLine1text": "Niezale&#380;ni",
    "headlineBarLine1axisXM": 50,
    "headlineBarLine1axisYM": 32,
    "headlineBarLine1axisXL": 50,
    "headlineBarLine1axisYL": 50,

    "headlineBarLine2text": "oszcz&#281;dzaj&#261; wiernie",
    "headlineBarLine2axisXM": 80,
    "headlineBarLine2axisYM": 78,
    "headlineBarLine2axisXL": 90,
    "headlineBarLine2axisYL": 112,

    "headlineBarLine3text": "",
    "headlineBarLine3axisXM": 0,
    "headlineBarLine3axisYM": 0,
    "headlineBarLine3axisXL": 0,
    "headlineBarLine3axisYL": 0,

    "imageSizeSSource": "https://content.ingbank.pl/files/x/nlf/koklkzt/xnjrkiktyj/ING_2020Q3_Cele_oszczednosciowe_Pies_Baner_600-x-232KV.jpg",
    "imageSizeSAriaDescibedBy": "",
    "imageSizeMSource": "https://content.ingbank.pl/files/x/nlf/koklkzt/uoqhovdisi/ING_2020Q3_Cele_oszczednosciowe_Pies_Baner_960-x-300KV.jpg",
    "imageSizeMAriaDescribedby": "",
    "imageSizeLSource": "https://content.ingbank.pl/files/x/nlf/koklkzt/rphobtnmnd/ING_2020Q3_Cele_oszczednosciowe_Pies_Baner_1232-x-400KV.jpg",
    "imageSizeLAriaDescribedby": "",

    "onclick":"https://adocean-pl.hit.gemius.pl/hitredir/id=..g6tfh3J0vOsy3bpgU1JZcP3wiIVoeOD5xGtybMjdP.f7/stparam=mfrtdwltxy/fastid=cnsdrgvcrpqrdfjumtsfunrpscml/sarg=5FD68952C6298C32/extra=;/url=https://www.ing.pl/lp/cele",
    "onview":"https://adocean-pl.hit.gemius.pl/redot.gif/id=..g6tfh3J0vOsy3bpgU1JZcP3wiIVoeOD5xGtybMjdP.f7/stparam=peknqisond/fastid=njamxelaaupptmmdxmunufxwucmq/sarg=5FD68952C6298C32/extra=;"
}
}
```

Czyli potem już nie ma odpytywania o plik i pewnie trzeba czyścić historię w domenie `gemius.pl` by zrobić lepszy test.

Więc redirect  w sumie można usunąć w tej chwili.

**Comment by krystian3w** [comment]
Do suplementu możemy dokopiować filtry `cname`:

`@@||ing.pl^$cname`
`@@||lubin.pl^$cname`

Jakby ktoś dezaktywował filtry `uBO - unbreak`, bo wtedy też obie strony mają jakieś uszkodzenia.

**Comment by krystian3w** [comment]
Naprawione przez https://github.com/olegwukr/polish-privacy-filters/commit/064d3d7bf185d311adc8879a0588f4a13b6b5d07 + https://github.com/olegwukr/polish-privacy-filters/commit/f6080227fd3c7b4c1f370d5b328a5966f6d73164#diff-cc474e426ece5e503e669e76f244564cb7218008ac11213fd82ac4c65ad3c494
