### ISSUE TITLE
wyborcza.biz

### ISSUE THREAD

**Issue by hawkeye116477** [olegwukr/polish-privacy-filters#127]
Anty-adblock

https://wyborcza.biz/biznes/7,177310,26561304,ktory-telewizor-jest-najlepszy-wielki-test-telewizorow-50-65.html?disableRedirects=true

![2020-12-24_19-37](https://user-images.githubusercontent.com/19818572/103103075-7ec98a80-461f-11eb-9d03-516d4cef33af.png)

**Comment by krystian3w** [comment]
https://github.com/olegwukr/polish-privacy-filters/commit/253531e0563101819d4f31a8a190576f57854af8
