### ISSUE TITLE
fakty.tvn24.pl

### ISSUE THREAD

**Issue by damianos56** [olegwukr/polish-privacy-filters#130]
Strona wykrywa ublock origin.

**Comment by damianos56** [comment]
Niestety fix nie działa. Nie ma komunikatu dot. adblocka, ale nie włącza się video.

**Comment by lain566** [comment]
@damianos56 Fixed. https://github.com/uBlockOrigin/uAssets/commit/9dca066063693ce0fd1a026185efcdc978d78a6a
Update your filter lists

**Comment by damianos56** [comment]
@lain566 thank you very much.
Videos work fine without ads ;)
