### ISSUE TITLE
ostatniatawerna.pl

### ISSUE THREAD

**Issue by hawkeye116477** [olegwukr/polish-privacy-filters#16]
![screenshot_20181208_000720](https://user-images.githubusercontent.com/19818572/49677143-5e045b80-fa7d-11e8-80c6-09a3b45d9fb1.png)

**Comment by MajkiIT** [comment]
Może coś takiego ?
```
ostatniatawerna.pl##[class$="-bg"]
ostatniatawerna.pl##[class$="-default"]
```

**Comment by hawkeye116477** [comment]
Tak w zasadzie, to wystarczy tylko `ostatniatawerna.pl#@##adsense`.

**Comment by MajkiIT** [comment]
@hawkeye116477 No masz rację :P
