### ISSUE TITLE
Forsal.pl - AntiBlock Detection Board 

### ISSUE THREAD

**Issue by billblitz1** [olegwukr/polish-privacy-filters#18]
### Screenshot
![obraz](https://user-images.githubusercontent.com/45767580/49748892-32fd5000-fca7-11e8-85f5-9eaf61fefbaa.png)

### Direct link
https://forsal.pl/

### What you need to do to get an element, an ad or an error
1. Go to forsal.pl
2. Adblock detection board will show after first scroll

### Configuration
**WebBrowser:**
firefox
chrome

**Extensions and scripts**
none

**Filter lists:**
1. EasyList
2. Official Polish List for Adblocka, uBlocka Origin i AdGuarda

**Comment by hawkeye116477** [comment]
`@@/js/adverts.js$domain=forsal.pl`

**Comment by MajkiIT** [comment]
https://github.com/olegwukr/polish-privacy-filters/commit/dea403a2ee8db75220ab581f15bf180e936f1667#diff-6de60f294b8bd23c752f8fcbece875b1
