### ISSUE TITLE
efizyka.net.pl

### ISSUE THREAD

**Issue by kulfoon** [olegwukr/polish-privacy-filters#20]
anty-adblock, to samo co tu (ściągawka) https://github.com/uBlockOrigin/uAssets/issues/3877#issue-374647031

![ss266](https://user-images.githubusercontent.com/43844449/49865124-62759f00-fe04-11e8-8857-4946b2be4911.png)

**Comment by olegwukr** [comment]
https://github.com/olegwukr/polish-privacy-filters/commit/f9eddec0924ebd8f15e781563c88a29a7da2aa50#diff-6de60f294b8bd23c752f8fcbece875b1
