### ISSUE TITLE
bh-res.pl

### ISSUE THREAD

**Issue by kulfoon** [olegwukr/polish-privacy-filters#21]
anty-adblock:

![ss264](https://user-images.githubusercontent.com/43844449/49865158-7faa6d80-fe04-11e8-9ff9-2688b9f47c1f.png)

**Comment by olegwukr** [comment]
https://github.com/olegwukr/polish-privacy-filters/commit/f9eddec0924ebd8f15e781563c88a29a7da2aa50#diff-6de60f294b8bd23c752f8fcbece875b1
