### ISSUE TITLE
mjakmama24.pl

### ISSUE THREAD

**Issue by xMaap** [olegwukr/polish-privacy-filters#31]
https://www.mjakmama24.pl/filmy/rozwarcie-szyjki-macicy-a-przebieg-porodu,0_mii62c23/
![opera zdjecie_2018-12-22_154408_www mjakmama24 pl](https://user-images.githubusercontent.com/36385327/50375610-72f5f880-0600-11e9-9572-f8a979d6ac78.png)

**Comment by krystian3w** [comment]
https://github.com/olegwukr/polish-privacy-filters/blob/ad0839d3f702eee4e47ad093b717c9a2428355a6/anti-adblock.txt#L246

Niby wystarcza ten jeden.
