### ISSUE TITLE
glosregionu.pl + ziemialeszczynska.pl + ziemiagorowska.pl (2)

### ISSUE THREAD

**Issue by kulfoon** [olegwukr/polish-privacy-filters#38]
Reopen, bo dalej to jest: https://github.com/olegwukr/polish-privacy-filters/issues/32, zarówno na Operze jak i Firefoxie.

**Comment by hawkeye116477** [comment]
`@@/js/adv.$script,domain=glosregionu.pl|ziemialeszczynska.pl|ziemiagorowska.pl`
