### ISSUE TITLE
biutiq.pl

### ISSUE THREAD

**Issue by kulfoon** [olegwukr/polish-privacy-filters#40]
Anty-adblock po najechaniu kursorem do lewej krawędzi strony:

![aa](https://user-images.githubusercontent.com/43844449/51140717-8d11a800-1847-11e9-96fd-12eb21d015e8.gif)

**Comment by krystian3w** [comment]
Problem częściowo zniknie po wycięciu, to widget social - "pinterest". Ale nie całe 14 milionów blokuje Social.

**Comment by MajkiIT** [comment]
@krystian3w masz to ?

**Comment by krystian3w** [comment]
Tak mam, nie chce ładować pluginu pinterest i podmienia go na tę grafikę z gifa.

**Comment by krystian3w** [comment]
To moje zdanie jest takie oni wykrywają:

`Polskie Filtry Społecznościowe​​​​​​​​​` i/lub `Fanboy’s Social Blocking List​​​​​​​​​` skoro wycinają te listy ten widget to ja to może zgłoszę do Fanboyów by u siebie wycieli i osoby blokujące social będą miały to z głowy na poziomie listy nadrzędnej do polskiego blokowania elementów social.

**Comment by krystian3w** [comment]
Chyba, że chcecie dodawać zbędny filtr:

`@@||assets.pinterest.com^$script,domain=biutiq.pl`

**Comment by garrgulowy** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/11335#issuecomment-454841928

> MajkiIT: garrgulowy A ty dalej po złości ?

1_ Raczej ty.

2_ A ty dalej lejesz hipokryzję? W kółko zadajesz to samo głupie pytanie, pomimo, że już wiele razy je zadawałeś np. tu https://github.com/MajkiIT/polish-ads-filter/issues/11257#issuecomment-454164939 a ja na nie odpowiadałem, więc jeśli przestałbyś po złości zarzucać mi, że to ja robię coś po złości, kiedy ty robisz po złości właśnie takimi pytaniami, to byłoby ok.

3_ A ty dalej zadajesz złośliwe pytania, na które nie da się odpowiedzieć, bo po ich zadaniu złośliwie szybko dajesz po cichu bana, robiłeś to już kiedyś i widzę robisz dalej, a ja ci już odpisywałem, że jeśli zadaje się komuś pytanie to tak żeby miał możliwość odpowiedzenia/obrony. I to nawet jeśli było pytanie retoryczne, bo i tak miało w sobie kłamliwe zarzuty. Bo przez to muszę odpisywać tutaj.

Jasno widać kto tu robi po złości, więc jeśli jeszcze raz po złości zadasz to głupie pytanie, że robię zgłoszenia po złości, na które to pytanie dodatkowo po złości uniemożliwiasz odpowiedzenie, to ci palnę w ten durny kaczan, robię zgłoszenia bo lubię, mam chcęć/zapał i jestem trochę uzależniony.

Dodatkowo oprócz ciebie, po złości robił admin tego repo oraz innych repo: 
https://github.com/gargaamel/polskie-ciasteczka-rodo-zgloszenia/issues/1#issuecomment-451486554 i w ogóle jest tam opisane zachowanie adminów, więc jeśli szukasz takich, którzy robią po złości to sam nim takim jesteś, a pozostałych znajdziesz we własnym gornie po fachu.

**Comment by hawkeye116477** [comment]
@garrgulowy A może przydałaby się tobie pomoc jakiegoś dobrego specjalisty. Bo skoro sporo już banów dostałeś od sporej liczby osób, to jednak jest coś nie tak, a pierwszy krok do wyleczenia to przyznanie, że ma się problem.

**Comment by garrgulowy** [comment]
Może wezwać ci kartekę pogotowia, wiele razy na nic nie zasłużyłem, a zachowywaliście się ohydnie, od jakiegoś czasu zacząłem dokumentować wasze chamstwo, i pokazywać ludziom, żeby wam płazem nie uchodziło, ta wasza bezkarna adminka, i żeby pokazać, że nie jesteście lepsi, a za takich się uważacie, po grzeczności z  wami nie da rady. Wam zostaje leczenie na nogi, bo na głowę to już za późno.
