### ISSUE TITLE
Inforamcja o ublock

### ISSUE THREAD

**Issue by kolor33** [olegwukr/polish-privacy-filters#41]
https://wiadomosci.dziennik.pl/polityka/artykuly/589231,giertych-wiadomosci-tvp-mowa-nienawisci-kurski-adamowicz-gdansk.html

**Comment by krystian3w** [comment]
U mnie czysto, μBlock 0.9.x / AdBlock / Adblock Plus lepiej wymienić na uBlock Origin:

https://addons.mozilla.org/pl/firefox/addon/ublock-origin/
https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=pl
https://addons.opera.com/pl/extensions/details/ublock/
https://safari-extensions.apple.com/details/?id=com.el1t.uBlock-3NU33NW2M3

**Comment by gwarser** [comment]
@kolor33 zaznacz obydwie polskie listy w ustawieniach uBO -> Listy filtrów -> Regiony, języki
