### ISSUE TITLE
https://operon.pl/Oferta

### ISSUE THREAD

**Issue by Mcinwwl** [olegwukr/polish-privacy-filters#42]
Bez wyłączenia uMatrix i uBlocka nie wyświetla się traść strony, tylko pasek menu na górze. Firefox 64.0.2 x64 pl, windows 7 pro pl, aktualny uBlock i uMatrix, obie polskie listy zaznaczone.

**Comment by gwarser** [comment]
```
Filter ##.push-wrapper
Filter list Fanboy’s Annoyance List 
```

operon.pl#@#.push-wrapper

**Comment by krystian3w** [comment]
Wkleić to co polecił @gwarser, a ja zobaczę czy Fanboy doda wyjątek do tej listy.

**Comment by Mcinwwl** [comment]
Działa, dzięki.
