### ISSUE TITLE
https://tvpstream.vod.tvp.pl/?channel_id=1455

### ISSUE THREAD

**Issue by kolor33** [olegwukr/polish-privacy-filters#46]
Proszę jak by się dało o odblokowanie .

https://tvpstream.vod.tvp.pl/?channel_id=1455

Widziany ublock

**Comment by MajkiIT** [comment]
@krystian3w masz to ?

**Comment by krystian3w** [comment]
Nie mam, może psuje się po 10 - 15 minutach, ale tak jest od roku.

**Comment by krystian3w** [comment]
@kolor33 w Firefox wyłącz funkcje ochrony prywatności przed śledzeniem:

https://support.mozilla.org/pl/kb/ochrona-przed-sledzeniem


Jak używasz dodatku Disconnect to też musi być wyłączony na "tvp vod".

**Comment by krystian3w** [comment]
Sprawdź takie coś @kolor33:
```
||tvp.pl/video/vod/reklamy/$domain=tvp.pl
||vod.*.tvp.pl/video/vod/reklamy/
@@||adx.adform.net/adx/$xmlhttprequest,domain=tvp.pl
@@||myao.adocean.pl^$image,domain=tvp.pl
@@||myao.adocean.pl/_*/ad.xml$xmlhttprequest,domain=tvp.pl
@@||myao.adocean.pl/*ad.*?$xmlhttprequest,domain=tvp.pl
@@||secure.adnxs.com/ptv?id=*&cb=*&pubclick=$xmlhttprequest,domain=tvp.pl
@@||adservice.google.pl/adsid/integrator.js$script,domain=tvp.pl
```

Jakby działało, to można przemyśleć uaktualnienie naszych blokad i dopuszczeń.

**Comment by kolor33** [comment]
No działa u mnie .

**Comment by krystian3w** [comment]
https://github.com/olegwukr/polish-privacy-filters/commit/c9477bc7ff203f07f2c5948ba4c3bafc082c62c8 brakująca reguła dodana, inna pod TVP przeniesiona do reszty.
