### ISSUE TITLE
filmweb

### ISSUE THREAD

**Issue by Humberd** [olegwukr/polish-privacy-filters#52]
![image](https://user-images.githubusercontent.com/10242142/52526110-41221980-2cb4-11e9-9a57-99795c22a2c8.png)

**Comment by raszpl** [comment]
```
filmweb.pl##script:inject(setTimeout-defuser.js, notDetected)
filmweb.pl##+js(abort-current-inline-script.js, Math.random, adbDetect)
```
przestaly lapac co trzeba. Znalazlem metode bruteforce, opcja nuklearna :

`filmweb.pl##+js(abort-current-inline-script.js, setTimeout)`

dziala :o)

**Comment by barabasz** [comment]
Dawniej działało (przy włączonym filtrowaniu kosmetycznym)
-filmweb.pl#@#+js(abort-current-inline-script.js, Math.random, adbDetect)
(i podobne dodatkowe wpisy).
Teraz nic nie pomaga. Niektórzy piszą o blokowaniu sascdn.com - u mnie to nic nie daje :(

**Comment by raszpl** [comment]
> Teraz nic nie pomaga.

wspomniane wczesniej 
`filmweb.pl##+js(abort-current-inline-script.js, setTimeout)`
wycina popup, ale blokuje niektore funkcje

**Comment by kulfoon** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/12017

**Comment by krystian3w** [comment]
Trzeba by wycofać filtry html (z daszkiem).

**Comment by krystian3w** [comment]
Kolejny raz trzeba poprawić jednak html filtering, zmula się repertuar kin a tam nie ma kodu anty-adblock:

```
filmweb.pl##^div[class^="pageBox "]:not([class="pageBox"]):not(.pageBoxS) ~ script:not([src])
filmweb.pl##^div[class^="pageBox"] ~ style
```
