### ISSUE TITLE
upflix.pl

### ISSUE THREAD

**Issue by kulfoon** [olegwukr/polish-privacy-filters#53]
Komunikat anty-adblock: https://upflix.pl/film/zobacz/marvels-the-avengers-2012

![ss_001](https://user-images.githubusercontent.com/43844449/53105156-e482f200-3530-11e9-9db2-bd3ce9ffea41.png)

**Comment by krystian3w** [comment]
`##.adblock-info`

**Comment by krystian3w** [comment]
`upflix.pl#@#.ad`

**Comment by krystian3w** [comment]
Do wyboru, do koloru.

**Comment by kulfoon** [comment]
Zamykam bo naprawione kilka dni temu i działa do dziś (więc przetestowane).

**Comment by kulfoon** [comment]
Otwieram ponownie, bo znowu się pojawiło.
