### ISSUE TITLE
dziennikwschodni.pl

### ISSUE THREAD

**Issue by kulfoon** [olegwukr/polish-privacy-filters#55]
Komunikat anty-adblock u góry:

![ss_013](https://user-images.githubusercontent.com/43844449/53349834-41f6b480-391e-11e9-8a97-be5d76495f20.png)

**Comment by krystian3w** [comment]
I adblock-wall w artykułach:

![obraz](https://user-images.githubusercontent.com/35370833/53360190-2c40b980-3935-11e9-83d8-71628cddf1d1.png) |
--- |


https://www.dziennikwschodni.pl/ryki/zarzuty-za-pobicie-na-komendzie,n,1000237986.html

**Comment by kulfoon** [comment]
Zamykam bo naprawione kilka dni temu i działa do dziś (więc przetestowane).

**Comment by gwarser** [comment]
Jak to było naprawione? Dzisiaj to mi pomaga `@@||dziennikwschodni.pl/*showads.js$xhr`

**Comment by krystian3w** [comment]
Oni chyba bawią się z tym jak filmweb więc działa tylko jak webmasterzy mają wolne/urlop.

**Comment by kulfoon** [comment]
> gwarser: Jak to było naprawione? Dzisiaj to mi pomaga `@@||dziennikwschodni.pl/*showads.js$xhr,first-party`

https://github.com/olegwukr/polish-privacy-filters/commit/97487756c099fb2e999c8d436afd2c43d9968b81#diff-6de60f294b8bd23c752f8fcbece875b1R307

Ale masz rację, że bez tego xhr to dalej wyskakiwało, okazało się, że mi nie wyskakiwało, bo naprawiał mi to Adguard Base Filters : `@@||dziennikwschodni.pl/*/showads.js`

A twój filtr xhr został też już szybko dodany:
https://github.com/olegwukr/polish-privacy-filters/commit/b23b5d3688282567e9866bed27fd60e1eb4454b8#diff-6de60f294b8bd23c752f8fcbece875b1R244

Więc już jest gitara.

**Comment by krystian3w** [comment]
Nie jest gitara, na innych też mają ten plik...

```
@@||pl^*showads.js$xhr
@@||eu^*showads.js$xhr
```

lub rozwiązanie z skryptem z 26 stycznia, dalej działa, jakby nie blokowali wszystkiego na maksa.

```
pl,eu##+js(set-constant.js, pp_adblock_is_off, trueFunc)
||s-pt.ppstatic.pl/*/reklama.js$script,redirect=noopjs,important
```

jedynie nie chce mi się robić listy ~40 domen powiązanych z Press Polska.

**Comment by kulfoon** [comment]
> krystian3w:  Nie jest gitara

Jest, jeśli chodzi o tę stronę/zgłoszenie, bo gitara odnosiła się do tej strony, ale skoro jest też na wielu innych to w takim razie robię reopen https://github.com/olegwukr/polish-privacy-filters/issues/27.
