### ISSUE TITLE
naszemiasto.pl

### ISSUE THREAD

**Issue by mijotek** [olegwukr/polish-privacy-filters#60]
Na przykład:
http://wroclaw.naszemiasto.pl/artykul/wypadek-pod-wroclawiem-z-auta-zostala-miazga-pasazerka-w,5056609,artgal,t,id,tm.html

**Comment by krystian3w** [comment]
Masz uBlock Origin / Nano Adblocker, tam jest to naprawione skryptem.

Pod Adblock Plus  / AdBlock chyba by trzeba raz na miesiąc poprawiać.

---

AdGuard chyba też to jakoś ogarnął by nie poprawiać co miesiąc.
