### ISSUE TITLE
interia.pl

### ISSUE THREAD

**Issue by kulfoon** [olegwukr/polish-privacy-filters#63]
Błąd w "Polish Privacy Filters​":

<details not-open>
<summary>Wycięta sekcja "Nieruchomości Z":</summary>

![ss_006](https://user-images.githubusercontent.com/48046250/55335408-5426be00-549b-11e9-8396-0094f1488045.png)

</details>
<details not-open>
<summary>Po wyłączeniu listy sekcja wraca:</summary>

![ss_005](https://user-images.githubusercontent.com/48046250/55335426-5721ae80-549b-11e9-9969-eac71bdd0d77.png)

</details>

**Comment by krystian3w** [comment]
Pewnie śledzące linki z przekierowaniem na sztywno w kodzie html.

**Comment by krystian3w** [comment]
Jak bardzo cię razi to to przywróci artykuły z śledzącym linkiem:

```
nieruchomosci.interia.pl#@#[href*=".hit.gemius.pl"]
@@||interia.hit.gemius.pl^$domain=nieruchomosci.interia.pl
```
