### ISSUE TITLE
shinden.pl

### ISSUE THREAD

**Issue by TechniKris** [olegwukr/polish-privacy-filters#64]
W UBO filtry: AdGuard Base filter, EasyList i Polskie filtry powodują uniemożliwienie wyświetlenia filmu (to samo jest na każdym anime/odcinku). 
![image](https://user-images.githubusercontent.com/30842158/55677124-6ca33800-58e2-11e9-81a3-34a59db3b345.png)
FuckFuckAdBlock nie daje efektów.

**Comment by MajkiIT** [comment]
@TechniKris podaj jakiś konrenty link

**Comment by TechniKris** [comment]
O jezu, miałem dołączyć linka, ale zagapiłem się, przepraszam :c

https://shinden.pl/episode/53156-tensei-shitara-slime-datta-ken/view/168297

Sytuacja dzieje się na każdej stronie z filmem, nie tylko tym anime

**Comment by MajkiIT** [comment]
@TechniKris Aktualizuj Polskie filtry reklam i sprawdź proszę.

**Comment by TechniKris** [comment]
Naprawione wszystko oprócz AdGuard Base filter. 👍

**Comment by MajkiIT** [comment]
@F4z usuniesz regułę ?
`shinden.pl#$#.ads { height: 203px!important; }`

**Comment by F4z** [comment]
Dzięki, usunięte.

**Comment by machond** [comment]
Problem już nie występuje po Waszych zmianach i aktualizacji ;)

**Comment by TechniKris** [comment]
Mhm, wygląda na to, że wszystko działa, zamykam. =)

**Comment by Castiell1986** [comment]
Hej!
Ja mam podobny problem co kolega sprzed 8 dni, tyle tylko że u mnie wyskakuje takie okienko, a filtry wszystkie oraz dodatek mam aktualny -.- 
![shinden](https://user-images.githubusercontent.com/49622169/56098773-61fd2a00-5f04-11e9-9d08-e263b0a4ab57.gif)

https://shinden.pl/episode/51844-kenja-no-mago/view/179722#column-one-inner

**Comment by MajkiIT** [comment]
@Castiell1986 jakie filtry ?

**Comment by TechniKris** [comment]
Co testowałem:
PC: Chrome, Vivaldi i Edge na wszystkie filtry domyślne UBO - nic nie wykrywa. ✔
Android: Chrome bez blokera (duh) - nic nie wykrywa. ✔
Android: Firefox, po włączeniu ochrony przed śledzeniem w ustawieniach przeglądarki, nawet bez blokera - wykrywa. ❌
Android: Firefox na wszystkie filtry domyślne UBO i Edge bez blokera - czasem wykrywa, czasem nie... ❔Wpływ może mieć Adaway. Próbowałem wyczaić Adawaya, ale z nim czasem mi wykrywa, czasem nie...

Wnioskuję stąd, że może być to być wina czegoś innego, niż któryś z filtrów UBO.

**Comment by Castiell1986** [comment]
> 
> 
> @Castiell1986 jakie filtry ?

mam tylko filtry domyślne. 
A te okienko nie pojawia się od razu, tylko po kliknięciu na pokaż przy każdym odcinku.

**Comment by TechniKris** [comment]
@Castiell1986 Sprawdź, czy nie masz włączonej ochrony przed śledzeniem w ustawieniach Firefoksa

**Comment by Castiell1986** [comment]
Śledzenie mam wyłączone. W  pracy teraz jestem i tu to samo jest.  Nawet chrome zainstalowałem i też to wyskakuje mi. Potraktowałem  Firefoxa ccleanerem oraz "odświeżyłem" przeglądarkę i też nie pomogło.

**Comment by TechniKris** [comment]
@Castiell1986 A bez UBO ci działa? 🤔 Jeśli tak to znaczy, że jednak wina któregoś z filtrów i musisz sprawdzić je po kolei.

**Comment by Castiell1986** [comment]
Bez ubo działa. Pobawię się w pracy i zobaczę czy wyłączenie którego z filtrów pomoże. Jak wrócę do domu po 21 to dam znać ;)
