### ISSUE TITLE
wyborcza.pl

### ISSUE THREAD

**Issue by hawkeye116477** [olegwukr/polish-privacy-filters#65]
Antyadblock „Odblokuj się! Odblokuj nas!"
`http://wyborcza.pl/7,90535,24571512,i-mrowki-znosza-zlote-jaja.html`
![Screenshot_20190407_114533](https://user-images.githubusercontent.com/19818572/55681783-b0219480-592a-11e9-971c-8bcef5ca41df.png)

**Comment by MajkiIT** [comment]
@hawkeye116477 Niestety tego nie mam

**Comment by hawkeye116477** [comment]
Hmm, dziwne, teraz też już tego nie mam.
