### ISSUE TITLE
Cookies/RODO - problemy.

### ISSUE THREAD

**Issue by seba2282** [olegwukr/polish-privacy-filters#72]
Witam, tak jak w temacie. Nieważne jaka przeglądarka, jaki dodatek i filtry - na wszelkich konfiguracjach nawet po akceptacji cookies/rodo, one pojawiają się co kilka godzin mimo iż ciasteczka nie były czyszczone uprzednio (po akceptacji). Najbardziej nieznośne jest dobreprogramy.pl ze swoim forum.dobreprogramy.pl i domenami wp. Jeszcze gdzieś tam między Rodo wsadzony jest gemius. 
Mało tego od czasu do czasu zaczęło się pojawiać tak samo RODO na spidersweb.pl/
Problem jest globalny i filtry polskie annoyances sobie nie radzą za dobrze. 

Czy dałoby się przyjrzeć sprawie i coś zrobić? 
P.S. Nawet I don't care about cookies lista i dodatek mają problemy.

**Comment by garggul** [comment]
Hmm dziwne, coś masz u siebie skopane albo jakiegoś syfa złapałeś, bo na wymienionych domenach nie wyskakują mi żadne ciasteczka ani rodo (poza reklamami na WP, ale to chyba już norma).

**Comment by seba2282** [comment]
@garggul, a sprawdzisz jeszcze na MS Edge na starym silniku? Tu jest największy problem. I chciałbym się dowiedzieć czy tylko u mnie. Najczęściej one się pojawiają po pewnym czasie i po odświeżeniu dobrych programów. System jest świeżo zainstalowany na nowo specjalnie dla wykluczenia syfu, o którym piszesz. 🙂

**Comment by krystian3w** [comment]
Mi na Androidzie dyfuzery @garggul działają z odświeniem strony (dobre programy i forum, może podobne coś zreprodukuje na homebook / domodi).

**Comment by seba2282** [comment]
@krystian3w, na Android już się uspokoiło. Ale wydaje mi się, że WP coś miesza w kodzie strony, bo na Edge na Windows wywala główną, jak na zrzucie załączonym na forum przez Radka. Na Edge wziąłem później X w celu zamknięcia tego Cookies/Rodo. Jest niby spokój, ale obserwuję temat, bo znowu może się to pojawić. Tak więc proszę jeszcze nie zamykać tematu. Sprawa wygląda najgorzej z Edge na starym silniku i przydałaby się drobna aktualizacja do dodatków ze sklepu Microsoft. Ale sądzę, że Adguard najszybciej da fix. 
Co bądź podejrzewam wp o majstrowanie i sprawdzanie, jak przyblokować Adblockery.

**Comment by garggul** [comment]
seba2282 spoko, nikt nie zamyka, ja wtedy https://github.com/olegwukr/polish-privacy-filters/issues/72#issuecomment-490792927 to tak tylko "na kolanie" sprawdziłem bo nie miałem za bardzo czasu bo musiałem wyjść, więc drugi raz się przyjrzę problemowi, tym razem dokładniej.

**Comment by krystian3w** [comment]
Na allegro podobno od rodo zepsuło się przewijanie.

**Comment by garggul** [comment]
Sprawdziłem drugi raz, ale nic to nie zmieniło, ten sam efekt, na komputerze stacjonarnym na Firefox i Opera z włączoną samą tylko listą Polskie Filtry Elementów Irytujących na kilku domenach które podałeś:

```
https://www.dobreprogramy.pl/
https://forum.dobreprogramy.pl/
https://www.wp.pl/
https://wiadomosci.wp.pl/
https://www.spidersweb.pl/
```

przy pierwszym wejściu nic nie wyskakuje typu ciasteczka czy rodo, a czy coś wyskoczy po paru godzinach/dniach, "po pewnym czasie i po odświeżeniu dobrych programów" nie wiem, czas pokaże, ale nigdy nie miałem tego typu problemów. Z Edge niestety nie korzystam.

=====================================================================

> krystian3w : https://github.com/olegwukr/polish-privacy-filters/issues/72#issuecomment-490877940 : Na allegro podobno od rodo zepsuło się przewijanie.

Tak, zgadza się, sprawdziłem na Firefox i Opera i zepsute jest przy włączonej liśćie Polskie Filtry Elementów Irytujących, natomiast przy samej tylko liście Polskie Filtry RODO-Ciasteczkowe DEV nie jest zepsute, więc błąd leży w samych filtrach irytujących i kwalifikuje się do zgłoszenia na tym repo: https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters.

**Comment by seba2282** [comment]
Acha, widzę, że jednak coś jest na rzeczy. Cookies/RODO, antiblocki i itp. Czyżby to celowa zagrywka w UE i PL? 😂 A tak na serio, wychodzi na to, że są różne konfiguracje i jednym działa - zero problemów, innym niedziała. Jakby team @MajkiIT i team @AdamWr połączyli pomysły na porządne reguły, to może problem by znikł. Bo UBO/Nano korzysta z filtrów AG i AG z filtrów UBO. Ale czy to możliwe?

**Comment by garggul** [comment]
seba2282 mam takie pytanie dlaczego ten wątek jest założony w tym repo, lub inaczej co ma ten problem z rodo/ciasteczkami wspólnego z tym repo, zgłoszenia rodo/ciasteczkowe zgłasza się na głównym repo: https://github.com/MajkiIT/polish-ads-filter/issues.

> seba2282 : https://github.com/olegwukr/polish-privacy-filters/issues/72#issuecomment-490885141 : Cookies/RODO, antiblocki i itp. Czyżby to celowa zagrywka w UE i PL?

Cookies/RODO nie są powiązane z anty-adblockami, 

o ile Cookies/RODO to zagrywka EU bo kilka lat temu wprowadzili przepisy wymuszające na twórcach stron wprowadzanie na stronach komunikatów informujących o korzystaniu przez stronę z funkcji ciasteczek i przetwarzania prywatnych danych.

to Anty-Adblocki to już prywatna decyzja właścicieli stron, nie ma przymusu umieszczania anty-adblocków na stronach internetowych. A że od jakiegoś czasu jest też wysyp anty-adblocków, to przypadek, po prostu coraz więcej osób korzysta z adblockerów więc coraz więcej stron się przed tym zabezpiecza.

seba2282 : (...) Ale czy to możliwe?

Fuzja uBO z AG, no pewnie, że możliwe, a czy w praktyce do tego dojdzie, to trzebaby zapytać wrózbty Davida: https://www.youtube.com/watch?v=M5CNivHfRGA

**Comment by seba2282** [comment]
@garggul, zastanawiam się czy ten błąd, co ja mam u siebie nie jest też spowodowany tym bugiem na filtrach irytujących. @krystian3w ma na allegro, ja mam na dobrych programach. Myślisz, że to może być to?

**Comment by garggul** [comment]
Możliwe, ale nie mam pojęcia czy to ten sam błąd czy dwa różne, bo ja na razie twojego błędu nie miałem.

**Comment by seba2282** [comment]
Już wyjaśniam. @krystian3w, zasugerował, aby zgłosić to do privacy, bo serio zaczęły się problemy z tym Rodo i nic nie blokowało. Ale teraz widzę, że to jednak wina po stronie irytujących. A tak się zarzekali, że filtry pracują dobrze, a w tym Rodo od wp siedzi gemius..

**Comment by garggul** [comment]
> seba2282 : https://github.com/olegwukr/polish-privacy-filters/issues/72#issuecomment-490897763 :  Ale teraz widzę, że to jednak wina po stronie irytujących.

Zakładając, że błąd z tym znikającym scrollem na Allegro to ten sam, co u ciebie z wyskakującymi Cookies/RODO.

**Comment by seba2282** [comment]
Sprawdzę na Edge z wyłączeniem irytujących polskich w AG i zostawię ciasteczka RODO aktywne, oraz wyczyszczę cookies i sprawdzę dobreprogramy. Jeżeli to, to mamy winowajcę. 🙂

**Comment by krystian3w** [comment]
No bo może warto dodać ten filtr sieciowy pod domeny gdzie nic nie psuje (np. poza sportowymi faktami).

**Comment by seba2282** [comment]
![2019-05-09 15 34 00](https://user-images.githubusercontent.com/16944478/57457488-ef1b7080-726f-11e9-935c-8e64f9aca260.jpg)
Niby tak trochę zaczyna działać z wszystkimi wbudowanymi + tymi dodatkowymi na fotce. Ale po odświeżeniu strony pokazuje się te rodo na Edge EdgeHtml. Tylko odświeżanie strony kuleje. Uważam, że winne są irytujące, I don't care about cookies i filtry wewnętrzne.

**Comment by garggul** [comment]
seba2282 rozumiem, że mówisz o tym twoim sprawdzeniu: https://github.com/olegwukr/polish-privacy-filters/issues/72#issuecomment-490899679, a czy próbowałeś z filtrem zaproponowanym przez krystian3w: https://github.com/olegwukr/polish-privacy-filters/issues/72#issuecomment-490908257.

**Comment by seba2282** [comment]
Sprawdzam właśnie go. :)

**Comment by seba2282** [comment]
Mam pytanie @krystian3w, czyli sportowe fakty są psute dalej?

**Comment by garggul** [comment]
> seba2282 : https://github.com/olegwukr/polish-privacy-filters/issues/72#issuecomment-490913548 Sprawdzam właśnie go. :) 

To dobrze, przynajmniej będzie komu testować nowe filtry pod ciasteczka/RODO, bo stare sprawiają sporo kłopotów https://github.com/MajkiIT/polish-ads-filter/issues/7533#issuecomment-489445023.

**Comment by seba2282** [comment]
Spróbuję teraz z adguard tą regułę, bo tylko on ukrywa permamentnie cały ten Avast i menadżer pobierania - czego nie robi ublock origin i nano adblocker po odświeżeniu strony w MS Edge. :)

**Comment by seba2282** [comment]
Działa na AG też. :)

**Comment by garggul** [comment]
To super, seba2282 czy mógłbyś w takim razie teraz mi pomóc tu: https://github.com/MajkiIT/polish-ads-filter/issues/13292 bo zaczepia mnie jeden, zależy mi na szybkiej rekacji.

**Comment by seba2282** [comment]
A, kojarzę tego pana. Poprosiłem kiedyś o regułę do ukrycia przycisków Facebook i Google przy logowaniu na dobreprogramy.pl, ale było, że ktoś ma problemy z logowaniem i niby fanboye już tego nie blokują.

**Comment by krystian3w** [comment]
https://github.com/olegwukr/polish-privacy-filters/issues/72#issuecomment-490914323 - nie są już psute, może stary regex blokował więcej niż 1 plik.

Za to `pilot.wp.pl` nie może mieć tego pliku blokowanego ani stary skrypt adguarda nie może tam być uruchamiany, bo włącza się anty-adblock.

**Comment by seba2282** [comment]
Czy ta reguła naprawiająca problem z cookies/rodo np. na starym Edge zamierza być dodana do filtrów?
I według mnie, kiboke coś nie chce aktualizować I don't care about cookies. Ostatni update z 27 kwietnia, gdzie fanboye miały update moment temu. Mowa od cookies.

**Comment by garggul** [comment]
> seba2282 : https://github.com/olegwukr/polish-privacy-filters/issues/72#issuecomment-491203918 : I według mnie, kiboke coś nie chce aktualizować I don't care about cookies. Ostatni update z 27 kwietnia, gdzie fanboye miały update moment temu. Mowa od cookies.

Oj żebyś się nie ździwił, jakiś czas temu to Fanboy miał przestój chyba z miesiąc: https://github.com/MajkiIT/polish-ads-filter/issues/12824#issuecomment-481762414

**Comment by seba2282** [comment]
Nie wiem który lepszy, ale kiboke w e-mail do mnie przyznał się, że jego lista nie działa jak należy.

**Comment by krystian3w** [comment]
A wysłałeś mu prośbę by rozszerzył wykrywanie domen WP, poza tymi co mają `.wp.pl`?

**Comment by seba2282** [comment]
@krystian3w, kto komu wysłał? 🤔🤔🤔

**Comment by krystian3w** [comment]
Do kiboke, bo pewnie dalej tylko na domenie `www.wp.pl` i coś`.wp.pl` pewnie dodatek zamyka.

**Comment by seba2282** [comment]
Wysłałem mu też twoją sugestię do zrobienia lepiej działającej listy, ale już nic nie odpisał.

**Comment by garggul** [comment]
> seba2282 : https://github.com/olegwukr/polish-privacy-filters/issues/67#issuecomment-491572371 : Wiem na pewno, że lista cookies od kiboke ma trochę negatywny wpływ na cookies i to może je rozwalać i tu pytanie.
> 
> @garggul i @krystian3w czy wy używacie I don't care about cookies?

Używam obydwu na raz: `Fanboy's Cookie List` + `I don't care about cookies` i obydwie czasem coś psują, ale najwięcej psuje Fanboy's Cookie List, i najwięcej uwalonych stron zgłaszałem właśnie z powodu tej listy, wystarczy spojrzeć na bug tracker Fanboy: https://github.com/ryanbr/fanboy-adblock/issues a tu np. same moje zgłoszenia: https://github.com/ryanbr/fanboy-adblock/issues/created_by/kulfoon, a tutaj moje super zgłoszenie, które możnaby oprawić w ramkę i na ścianie na łóżkiem zawiesić - w tym zgłoszeniu ponad 300 stron uwalonych https://github.com/ryanbr/fanboy-adblock/issues/976 chociaż nie polskich.

**Comment by seba2282** [comment]
@garggul, ciekawe. :)

**Comment by krystian3w** [comment]
Ja nie używam, to generalnie przeszkadza w sprawdzaniu czy cookies wycina polska lista.

Raczej długo nikt nie podepnie jako bazy `Fanboy's Cookie List` / `I don't care about cookies`.

A twór AdGuard Cookies nie istnieje i nie jest w 100% kompatybilny z uBO, choćby z przyczyny metody wyłączania filtrów dla uBO:

```
!+ PLATFORM(!ext_ublock)
```

uBO tego nie rozumie a na pewno nie trafi takie coś do uBO w przyszłości do sprawdzania jako warunek.

**Comment by seba2282** [comment]
Adguard dostał fix na filtrach i nawet odświeżenie strony nie powoduje problemów w MS Edge. :D

**Comment by krystian3w** [comment]
Podobno filtry cookies psują tinder `https://tinder.com/?lang=pl`

**Comment by seba2282** [comment]
Nie widzę. Chyba jest normalnie z AG.

**Comment by seba2282** [comment]
@krystian3w, skorzystałem z blokady reklamy w Adguard i widzę, że na razie na problem z tinder działa reguła:
 tinder.com###modal-manager

**Comment by krystian3w** [comment]
A niby wydali ci AdGuard 3.1.X? Jak plik ma już inną nazwę to trzeba odkopać stary regex na "`{460}`" znaków.

**Comment by seba2282** [comment]
Nie napisałem nic o AG 3.1 :P Ale do rzeczy. Chciałem podać tu regułę, która zablokowała te cookies jako blokuj element w AG, ale spojrzałem i próba kliknięcia zaloguj/rejestruj na tinder nie działała.

**Comment by krystian3w** [comment]
Nie ma jeszcze. A dopiero wtedy dla mas wrócą AdGuardowe filtry skryptowe w Edge.

**Comment by seba2282** [comment]
@krystian3w, czyli można załatwić skryptowymi filtrami bez niepewnych dodatków. 😂

**Comment by krystian3w** [comment]
Plik na tinderze przebudowali już w lutym: https://github.com/ryanbr/fanboy-adblock/issues/950#issuecomment-466758171

Widać w Polsce nikt nie używa wersji WWW...

**Comment by seba2282** [comment]
@krystian3w, no cóż, jesteśmy inni :P

**Comment by seba2282** [comment]
> No bo może warto dodać ten filtr sieciowy pod domeny gdzie nic nie psuje (np. poza ~sportowymi faktami~ `pilot.wp.pl`).
> 
> ```
> ||wp.pl/*-FwkqOxhmGz4XCSo7GGYbPhcJKjsYZhs-$script,domain=~pilot.wp.pl
> ```
> 
> reguła wygeneruje anty-adblock na `pilot.wp.pl`... bywa 😭

@krystian3w, AdamWr coś wspomniał, że ta reguła była w polskich filtrach w styczniu i @MajkiIT ją usunął. Dlaczego?

**Comment by krystian3w** [comment]
Reklamowych? Jak tak to pewnie przez przypadek, a jak myślał o repozytorium dev to się nie liczy, że tam było bo nie dodarło do MajkiIT.

**Comment by krystian3w** [comment]
Jest też opcja że psuło coś więcej poza `pilot.wp.pl` to lepiej było wycinać kosmetycznie reklamy.

**Comment by seba2282** [comment]
Pytanie do @MajkiIT. Dlaczego usunąłeś tą regułę?
