### ISSUE TITLE
twojapogoda.pl

### ISSUE THREAD

**Issue by garggul** [olegwukr/polish-privacy-filters#75]
Anty-adblock : https://github.com/olegwukr/polish-privacy-filters/issues/67#issuecomment-491535008

na Firefox i Opera, przy pierwszym wejściu jest ok i filmik (progonza pogody)  u góry po prawej się odtwarza, a przy odświeżeniu strony i następnych odświeżeniach strony już nie bo:

<details not-open>
<summary> sypie Anty-Adblockiem:</summary>

![SS_021](https://user-images.githubusercontent.com/50133507/57573748-1ff4d480-742d-11e9-92e5-ba5104ba35ad.png)

</details>

Pomaga włączenie którejś z list:
- AdGuard Base List
- Polskie Filtry RODO-Ciasteczkowe
- Polskie Filty Elementów Irytujących

więc można z nich wyciągnąć regułę.

**Comment by krystian3w** [comment]
pogodynka?

**Comment by garggul** [comment]
> garggul : https://github.com/olegwukr/polish-privacy-filters/issues/75#issue-443025334 : Pomaga włączenie listy: AdGuard Base List, więc można stamtąd wyciągnąć regułę,

Wyciągnąłem ją: `@@||redefineadpl.hit.gemius.pl/*redataredir?url=*ipla.hit.stat24.com*ad.xml$domain=polsatnews.pl|polsatsport.pl|twojapogoda.pl`

**Comment by krystian3w** [comment]
Mnie bez niej po odświeżeniu dalej ładuje prognozę, z 100 razy odświeżać nie mogę by to złapać.

**Comment by garggul** [comment]
Może obraźliwe pytanie ale czy czyściłeś ciasteczka & pamięć podręczną, jak dalej nie możesz zreprodukować to może podaj swoje listy.

**Comment by krystian3w** [comment]
Czyszczone, 3 odświeżenia, brak wykrycia anty-adblock w Firefox.

![obraz](https://user-images.githubusercontent.com/35370833/57582881-97c50c80-74ca-11e9-8a50-272db5d81781.png) |
--- |

Na pewno pingwin tego nie naprawia ani magia kompresji Norwega.

**Comment by bogachenko** [comment]
@garggul 

test
```
@@||stat24.com/*/ad.xml$xmlhttprequest,domain=twojapogoda.pl
@@||stat24.com/ad.xml$xmlhttprequest,domain=twojapogoda.pl
@@||stat24.com/*/ad.js$script,domain=twojapogoda.pl
```

if it doesn't help at all, try heavy artillery

`@@||stat24.com^$domain=twojapogoda.pl`

**Comment by garggul** [comment]
To ja nie wiem jak ty testujesz anty-adblocki, skoro nawet nie wyłączasz dodatkowych list..., przy włączonej liście Polskie Filtry RODO-Ciasteczkowe DEV nie ma anty-adblocka, po wyłączeniu tej listy jest, i w ogóle to trochę dziwne, bo przy włączonej tej liście nie filttr z tej listy uwala anty-adblocka, tylko aktywuje się filtr z innej listy:
https://github.com/olegwukr/polish-privacy-filters/blob/ef361621a65fd579160c1dd33804127c2e67a73e/anti-adblock.txt#L263

**Comment by bogachenko** [comment]
this one filter (with default settings and 2 Polish lists) does not work for me. Antiblock still there

`@@||ipla.hit.stat24.com/*ad.xml$xmlhttprequest,domain=polsatnews.pl|polsatsport.pl|twojapogoda.pl`

**Comment by krystian3w** [comment]
Bo to się przydaje do sprawdzana co naprawił pingwin a nam nie napisał, wtedy on po czasie może ze swojej usunąć, czasem też usuwa z kodu dodatku coś, co działa dobrze jako `set-constant.js` a on to sobie wrzucił w dodatek jakby się bał race condition.

**Comment by garggul** [comment]
> bogachenko : https://github.com/olegwukr/polish-privacy-filters/issues/75#issuecomment-491599221 :
>
> this one filter (with default settings and 2 Polish lists) does not work for me. Antiblock still there
> 
> `@@||ipla.hit.stat24.com/*ad.xml$xmlhttprequest,domain=polsatnews.pl|polsatsport.pl|twojapogoda.pl`

It does not work for me too, it's weird but, if you enable additional list: 
https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/cookies_filters/adblock_cookies.txt

Suddenly the filter is working... and there is no anti-adblock anymore.

> krystian3w : https://github.com/olegwukr/polish-privacy-filters/issues/75#issuecomment-491599429 : 
> 
> Bo to się przydaje do sprawdzana co naprawił pingwin a nam nie napisał, wtedy on po czasie może ze swojej usunąć, czasem też usuwa z kodu dodatku coś, co działa dobrze jako `set-constant.js` a on to sobie wrzucił w dodatek jakby się bał race condition.

Ja nie miałem włączonego Nano Defendera ani tylu dodatkowych list co ty, tylko Polish Privacy Filters.

**Comment by garggul** [comment]
Potwierdzam - naprawione, więc zamykam.
