### ISSUE TITLE
magazyn.wp.pl

### ISSUE THREAD

**Issue by xMaap** [olegwukr/polish-privacy-filters#81]
![Screenshot_20190526_011040](https://user-images.githubusercontent.com/36385327/58375429-26b63800-7f53-11e9-991b-97f994395cf1.png)

**Comment by krystian3w** [comment]
kolejne też to mają:

 https://ksiazki.wp.pl/tomasz-organek-zyjemy-w-czasach-kryzysow-tozsamosci-6383724550961281a

**Comment by krystian3w** [comment]
```
magazyn.wp.pl##body > div ~ footer ~ script +script + div[class]:not([id]):last-of-type
```

```
ksiazki.wp.pl##body > #app ~ script + noscript + div[class]:not([id])
```

**Comment by krystian3w** [comment]
Na sportowych faktach:

```
sportowefakty.wp.pl##body > .content ~ iframe + div[class]:not([id])
sportowefakty.wp.pl##body > .content ~ script[async] + div[class]:not([id])
```

na kolejne:

```
magazyn.wp.pl##body > div ~ footer ~ script + script + div[class]:not([id]):last-of-type
```

```
ksiazki.wp.pl##body > #app ~ script + noscript + div[class]:not([id])
```

Cech wspólnych za bardzo nie ma..., skrypty nie mają atrybutu [async]  ani nie widzę w dole strony "ramek"...

**Comment by krystian3w** [comment]
Teraz pojawił się też na wiadomosci.wp.pl:

https://github.com/AdguardTeam/AdguardFilters/commit/e3e698cd98be3512981d77359e074b586a2de0a7

**Comment by xMaap** [comment]
Na sportowefakty coś zmienili i znowu nie działa. Włączyłem filtr AdGuard Base List i ukrywa. 

Szkoda, że filtry od AdGuard tylko takie coś blokują, a reklam na takim WP nawet nie tykają.

**Comment by krystian3w** [comment]
Bo nie ma instrukcji replace i możliwości konwersji skryptów AdGuard natywnie (trzeba ręcznie pokombinować co działa podobnie z uBo i nie uwala np. komentarze).

**Comment by xMaap** [comment]
Właśnie zauważyłem, że AdGuard Base List niektóre filmy na WP po prostu blokuje.

**Comment by krystian3w** [comment]
Na sportowych faktach zniknął iframe:

https://github.com/AdguardTeam/AdguardFilters/commit/d6056539568432819bacf19b26b9d4c2adc5e7d8

**Comment by krystian3w** [comment]
Na anty-adblock na pilot.wp.pl z AdGuard Base rozwiązanie:

```
pilot.wp.pl##html > body > div.pub_300x250.text_ads.ad_container[style]:not(#page):style(display: block!important;)
```

**Comment by krystian3w** [comment]
WP przebudowało link w pop-upie:

https://github.com/AdguardTeam/AdguardFilters/commit/04b8ac45210fc0975bb8d1a7ba168a4de065218f

**Comment by krystian3w** [comment]
```
film.wp.pl,finanse.wp.pl,kobieta.wp.pl,ksiazki.wp.pl,magazyn.wp.pl,opinie.wp.pl,sportowefakty.wp.pl,teleshow.wp.pl,wiadomosci.wp.pl#?#body > div[class][id]:has(div[class]:matches-css-before(content:"Nie teraz, wracam na WP.pl"))
```

PS. *sNie można pominąć cudzysłowów**.

**Comment by krystian3w** [comment]
`http://eveline.wp.pl/cztery-kroki-dla-wypoczetej-cery`

Jakiś komunikat anty-adblock

**Comment by krystian3w** [comment]
`sportowefakty.wp.pl##body > div:matches-css(position: fixed):matches-css(top: 0px)`

dołożyli jakby z klika div-ów lub spacje 0 szerokości.

**Comment by krystian3w** [comment]
```
sportowefakty.wp.pl##body [class]:matches-css(position: fixed):matches-css(top: /^0\..*px$/)
```

Pewnie zmienią nagle pozycjonowanie, uwolnią obiekt od klasy CSS, zmienią jednostkę z pikseli na coś...

**Comment by MajkiIT** [comment]
Coś nie łapie niestety :(

**Comment by krystian3w** [comment]
Mobilny player wykrywa anty-adblock:

```
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=parenting.pl|abczdrowie.pl|money.pl
```
<sub>

https://parenting.pl/jaka-rybe-wybrac-na-wakacjach-nad-baltykiem-wideo <br>

https://portal.abczdrowie.pl/choroba-konskiego-ogona-zagraza-posiadaczom-dlugich-wlosow-nie-wiaz-wlosow-w-kucyk-wideo

</sub>

**Comment by krystian3w** [comment]
```js
!#if cap_user_stylesheet
magazyn.wp.pl##div:has(div > img[src*="NDM0MzY2YSUsUjtJdklsMG8KbxkpWhE3OVRvVntHbH5vHyQXOFUrN2JRLBh2XCcmY0AjHXtP"])
magazyn.wp.pl##body:style(overflow: auto !important;)
!#endif
magazyn.wp.pl##+js(overlay-buster.js)
```

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/14506#issuecomment-524755555

**Comment by xMaap** [comment]
`https://wiadomosci.wp.pl/trump-nominuje-polske-do-programu-bezwizowego-co-to-oznacza-w-praktyce-6418439724000897a
`
![Zrzut ekranu z 2019-08-28 21-50-59](https://user-images.githubusercontent.com/36385327/63887825-efd24100-c9dd-11e9-84a7-fe2703207276.png)

**Comment by krystian3w** [comment]
Blur może być z rodo, najpierw trzeba by usunąć filtr na sieciowe wywalanie RODO, potem overlay-buster, następnie może dalej bawić się

**Comment by xMaap** [comment]
```
https://www.pudelek.pl/
https://www.o2.pl/
```
![Zrzut ekranu z 2019-08-28 23-19-33](https://user-images.githubusercontent.com/36385327/63893409-5e1d0080-c9ea-11e9-8993-fc669610b1da.png)

**Comment by krystian3w** [comment]
Na pudelku nie może być `overlay-buster`, chyba że czytasz nagłówki i obrazki i nie komentujesz "zgól koper chłopcze".

**Comment by xMaap** [comment]
```
https://www.o2.pl/
https://wiadomosci.wp.pl/
https://wawalove.wp.pl/
https://finanse.wp.pl/
https://sportowefakty.wp.pl/
https://opinie.wp.pl/
https://kobieta.wp.pl/
https://facet.wp.pl/
https://moto.wp.pl/
https://www.pudelek.pl/
https://gwiazdy.wp.pl/
https://kuchnia.wp.pl/
https://turystyka.wp.pl/
https://film.wp.pl/
https://tech.wp.pl/
https://ksiazki.wp.pl/
https://teleshow.wp.pl/
```
![Zrzut ekranu z 2019-09-13 13-06-05](https://user-images.githubusercontent.com/36385327/64858617-2fc53500-d628-11e9-8751-f3e5506a9cd7.png)

**Comment by krystian3w** [comment]
Maskowanie jako Google Bot / smartfon lub odblokowanie reszty reklam 😥

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/64874195-d7ebf580-d64a-11e9-8de5-c401109f72f3.png)


```
@@/js/ads.js$domain=oppo.wp.pl
```

`http://oppo.wp.pl/harmonia-innowacji-z-designem-oto-oppo-czyli-jeden-z-najwiekszych-producentow-smartfonow-na-swiecie`

**Comment by krystian3w** [comment]
Na `magazyn.wp.pl` pomaga.

```
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=wp.pl|o2.pl|pudelek.pl|so-magazyn.pl
@@||googletagservices.com/tag/js/gpt.js$domain=wp.pl|dobreprogramy.pl|o2.pl|pudelek.pl|so-magazyn.pl
magazyn.wp.pl#@#+js(set-constant, Object.prototype.aggressiveAB, false)
magazyn.wp.pl#@#+js(set-constant, Object.prototype.isBlocked, false)
! #@#+js(overlay-buster)
magazyn.wp.pl#@#+js(abort-on-property-write, __serviceAbModal)
magazyn.wp.pl#@#+js(set-constant, PWA_adbd, 2)
magazyn.wp.pl#@#+js(set-constant, WP.gaf.loadBunch, noopFunc)

wp.pl#@#html, html > body:style(overflow: auto !important;)
wp.pl#@#body:style(overflow: auto !important;)
wp.pl#@#body [class]:style(filter: none !important;)
wp.pl#@#body:style(pointer-events: auto!important;)
wp.pl#@#body > [class]:style(filter: none!important;)
wp.pl#@#body:style(overflow: visible!important;)
wp.pl#@#body > div:nth-of-type(1)[style^="display: block;"]:not(#page)
```
