### ISSUE TITLE
kulturalnemedia.pl

### ISSUE THREAD

**Issue by hawkeye116477** [olegwukr/polish-privacy-filters#84]
`https://kulturalnemedia.pl/strona-glowna/summer-sale-festival-2019/`
![Screenshot_20190601_220352](https://user-images.githubusercontent.com/19818572/58753042-2b31a200-84b9-11e9-8a88-0ff92dc45137.png)

**Comment by krystian3w** [comment]
generichide lub adOptions.

**Comment by krystian3w** [comment]
wabik to niby:

`kulturalnemedia.pl#@##adsense`

**Comment by krystian3w** [comment]
Powiązane: https://github.com/olegwukr/polish-privacy-filters/issues/86
