### ISSUE TITLE
A: snrbox.com, snrcdn.net

### ISSUE THREAD

**Issue by trackerless** [olegwukr/polish-privacy-filters#93]
Advanced browser fingerprinting and analytics.

Spotted on:
https://www.eobuwie.com.pl/

#92

**Comment by krystian3w** [comment]
https://github.com/olegwukr/polish-privacy-filters/commit/25ab0eb1c9c4a463edf64c52a2e330d563f9429f

**Comment by krystian3w** [comment]
#149 #147
