### ISSUE TITLE
newonce.net

### ISSUE THREAD

**Issue by hawkeye116477** [olegwukr/polish-privacy-filters#98]
![Screenshot_20190829_203108](https://user-images.githubusercontent.com/19818572/63966637-fd4e0080-ca9b-11e9-91f8-e2713fb27c8e.png)

**Comment by krystian3w** [comment]
raczej generichide i trzeba ocenić wyciek socialu.

**Comment by hawkeye116477** [comment]
Albo odblokować reklamę => `newonce.net#@##adsense` :smiley:

**Comment by krystian3w** [comment]
To tylko w AdGuard, a mało kto używa `AdGuard base` w Polsce z uBO.

---

 @alex-302 can you fix with:

```
newonce.net#@##adsense
```

**Comment by hawkeye116477** [comment]
@krystian3w Nieprawda.
`https://github.com/olegwukr/polish-privacy-filters/blob/master/anti-adblock.txt#L21`

**Comment by krystian3w** [comment]
Prawda: 

https://github.com/olegwukr/polish-privacy-filters/blob/7f3077ef58b1115f383cce4766b75018260633a1/anti-adblock.txt#L291
https://github.com/olegwukr/polish-privacy-filters/blob/7f3077ef58b1115f383cce4766b75018260633a1/anti-adblock.txt#L317




ten niby niedodany, bo niby ND naprawia to olano.
```
@@||szydlowiecki.eu^$generichide
```

**Comment by Alex-302** [comment]
> can you fix with:

https://github.com/AdguardTeam/AdguardFilters/commit/80d04f8d78c93a31e6a322738a3a0b807c86e121
